name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  ZIP_FILE: tmpl-${RUNNER_OS}-${RUNNER_ARCH}.zip


jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21.1'
      - name: Build
        run: |-
          echo ${{ github.sha }} > Release.txt
          go build -v -o tmpl
          zip "${{ env.ZIP_FILE }}" tmpl
      - name: Test
        run: ls -l;file "${{ env.ZIP_FILE }}"
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./src/tmpl-Linux-X64.zip
          fail_on_unmatched_files: true